version: "3.9"

services:
  # Production build
  prod:
    build:
      context: ./
      network: host
    volumes:
      - ./.git:/home/app/.git
      - ./dist:/home/app/dist
    profiles:
      - prod

  # Development server
  dev:
    build:
      context: ./
      network: host
    expose:
      - '5000'
    ports:
      - '5000:5000'
    volumes:
      - ./.git:/home/app/.git
      - ./dist:/home/app/dist
    entrypoint: ["npm", "run", "dev"]
    profiles:
      - dev
