version: "3.9"

services:
  # Production build
  prod:
    build:
      context: ./frontend/
      # network: host
    volumes:
      - ./.git:/home/app/.git
      - ./dist:/home/app/dist
    profiles:
      - prod

  # Development server
  dev-frontend:
    build:
      context: ./frontend/
      # network: host
    expose:
      - '9090'
    ports:
      - '9090:9090'
    volumes:
      - ./.git:/home/app/.git
      - ./frontend:/home/app/frontend
    entrypoint: ["npm", "run", "dev"]
    profiles:
      - dev

  dev-backend:
    build:
      context: ./backend/
      # network: host
    expose:
      - '8080'
    ports:
      - '8080:8080'
    volumes:
      - ./.git:/home/app/.git
      - ./backend:/home/app/backend
    environment:
      - FLASK_APP=server.py
      - FLASK_ENV=development
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=8080
    profiles:
      - dev
