version: "3.9"

services:
  # Production build
  prod:
    build:
      context: ./frontend/
      # network: host
    volumes:
      - ./.git:/home/app/.git
      - ./dist:/home/app/dist
    profiles:
      - prod

  # Development server
  dev-frontend:
    build:
      context: ./frontend/
    expose:
      - '9090'
    ports:
      - '9090:9090'
    volumes:
      - ./.git:/home/app/.git:ro
      - ./frontend/assets:/home/app/assets:ro
      - ./frontend/scss:/home/app/scss:ro
      - ./frontend/svelte:/home/app/svelte:ro
      - ./frontend/ts:/home/app/ts:ro
    entrypoint: ["npm", "run", "dev"]
    profiles:
      - dev

  dev-backend:
    build:
      context: ./backend/
    expose:
      - '8080'
    ports:
      - '8080:8080'
    volumes:
      - ./.git:/home/app/.git:ro
      - ./backend:/home/app/src/:ro
    environment:
      - FLASK_APP=src/server.py
      - FLASK_ENV=development
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=8080
    profiles:
      - dev
