version: "3.9"

services:
  # Production build
  prod-frontend:
    build:
      context: ./frontend/
    volumes:
      - ./.git:/home/app/.git:ro
      - ./dist/static:/home/app/dist:rw
    profiles:
      - prod
  prod-backend:
    build:
      context: ./backend/
    volumes:
      - ./.git:/home/app/.git:ro
      - ./dist:/home/app/dist:rw
    profiles:
      - prod

  # Development server
  dev-frontend:
    build:
      context: ./frontend/
    expose:
      - '9090'
    ports:
      - '9090:9090'
    volumes:
      - ./.git:/home/app/.git:ro
      - ./frontend/assets:/home/app/assets:ro
      - ./frontend/scss:/home/app/scss:ro
      - ./frontend/svelte:/home/app/svelte:ro
      - ./frontend/ts:/home/app/ts:ro
    entrypoint: ["npm", "run", "dev"]
    profiles:
      - dev

  dev-backend:
    build:
      context: ./backend/
    expose:
      - '8080'
    ports:
      - '8080:8080'
    volumes:
      - ./.git:/home/app/.git:ro
      - ./backend:/home/app/src:ro
    environment:
      - FLASK_APP=src/server.py
      - FLASK_ENV=development
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=8080
    entrypoint: [ "pipenv", "run", "python", "src/server.py" ]
    profiles:
      - dev
